### ISSUE TITLE
Handeling Edge-cases

### ISSUE THREAD

**Issue by boggs** [oitsjustjose/CPSC4100#3]
We need to determine how we are going to handle invalid commands. I see two types of invalid commands a user could provide:

* Initially invalid commands. EX: `draw_hoizontal_line, -10, -10, 10`
* Eventually invalid commands, these would start in valid board-space and attempt to draw off the edge. EX: `draw_horizontal_line, 10, 10, 9999`

**Comment by boggs** [comment]
I vote we just no-op in both cases. If a command starts invalid, we do nothing.
If a command starts drawing off the edge, we simply stop drawing.

**Comment by oitsjustjose** [comment]
I've no-op'd invalid inputs on my part :smile:
