### ISSUE TITLE
Should be board size be configurable?

### ISSUE THREAD

**Issue by boggs** [oitsjustjose/CPSC4100#5]
Currently we hard-code the board-size at 32x32, should this be configurable with a command?

`board_size x_dimension, y_dimension`

**Comment by oitsjustjose** [comment]
My vote is no - I think that's complicating things further than they need to be in the end. The easier we can make this project, the better.

**Comment by boggs** [comment]
I like this answer, lets keep the current size, and have it be non-configurable.
