### ISSUE TITLE
Do we allow the fill character to be specified?

### ISSUE THREAD

**Issue by boggs** [oitsjustjose/CPSC4100#6]
Right now the fill-character is hard-coded to be '@', should we allow this to be configurable?

**Comment by boggs** [comment]
Actually, per the instructions we have to allow the fill character to be provided.

I suggest we go with: `fill x_cord, y_cord, fill_char`.

**Comment by oitsjustjose** [comment]
👍 works for me.

**Comment by oitsjustjose** [comment]
My python version has implemented this. I suspect yours will soon too, and the other new ones should fall suit.

**Comment by boggs** [comment]
Yup, we need fill characters. Lets do it.
